name: "CI Multiplatform Build"

# This is an example of a CI workflow that builds the project on all desktop platforms

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: "CI Multiplatform Build"
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: apt install xorg-dev  libglfw3-dev (ubuntu only)
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install -y xorg-dev  libglfw3-dev

    - name: Build
      run: |
        mkdir build 
        cd build
        cmake .. -DHELLOIMGUI_DOWNLOAD_FREETYPE_IF_NEEDED=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
